### ISSUE TITLE
tests and examples not included in PyPI package

### ISSUE THREAD

**Issue by onyx-and-iris** [Julian-O/PySLOBS#1]
Hi, fantastic work on this wrapper! I installed with pip and it threw error: No module named 'tests'

Just a small thing, thought you'd like to know.

**Comment by Julian-O** [comment]
Hmmm... I am not getting this on installation. My guess is you are running one of the examples, which has an unfortunate dependency on tests.

I didn't intend for the pip installation to include examples and tests. Maybe that needs a rethink.

I will need to look into:
- Making the examples stand-alone, so they don't depend on test?
    - Consider adding the ability to read the token from environment variables to the API, so examples and 
      tests don't need to implement their own system.
- What standard practice is for including example code.
   - Should I make an option to `pip install pyslobs[examples]`?

In the meantime, the dependency is just to find the token; if you want to proceed quickly, you can replace the call to `token()` in the example with a hard-coded API token as a string.

Thanks for checking it out. Let me know if you find anything difficult to understand or use.

**Comment by onyx-and-iris** [comment]
Yes I should be more clear, I did try running one of the examples. In the end I just pulled the files from git and copied examples and tests over.

If it's not intended that the pip files include test and examples then I would suggest you remove the reference to Examples on the PyPI page, that was a bit confusing. It says there:

_Examples:
The examples folder contains many small programs to demonstrate how to use the API.

See tests\config.py for instructions on authentication_

Otherwise yes, perhaps an option to also install examples would benefit others.

Thanks for your time and quick response.

**Comment by Julian-O** [comment]
In V1.1.0, I have made several changes to fix this.

1. Specified that the examples are *not* installed, and given instructions on where to find them.
2. Introduced the concept of ini files as part of the API, which subsumes `tests\config.py`, so I can remove that.
3. Modify the examples to remove the dependency on the test code. They should now all be stand-alone (with the just the PySLOBS library installed).
