### ISSUE TITLE
Can I control someone else's OBS?

### ISSUE THREAD

**Issue by hiro-551010** [Julian-O/PySLOBS#10]
I'm sorry for asking  personal questions again.
I'm thinking of getting someone else's API token to control it.
Is this technically possible?
If you could do that, what do you think you would need?

Thank you in advance!

**Comment by Julian-O** [comment]
Yes it is possible.  The ReadMe explains:

> OBTAINING CONNECTION DETAILS
>
> To obtain all these details, start Streamlabs OBS, open the settings page, and select "Remote Control". A (blurry) QR code will be displayed. Do not show that QR code on your stream.
>
> If you click on the QR code, and click "Show Details" underneath it, you will be given the following details:
>
> * API token
>
> * Port: This should default to 59650. If it is a different value, your Python application will need to know this.
>
> * IP addresses: **If your application is on a different host to Streamlabs OBS, your Python application will need to know one of the IP addresses offered**.

Your network will need to be able to open a connection to the given IP address. I predict this will be the hardest part if you aren't on the same subnet, but you need a network expert to help with this; it is nothing to do with PySLOBS or StreamLabs OBS.
