### ISSUE TITLE
Is it possible to change the visibility of sources?

### ISSUE THREAD

**Issue by IC0okieI** [Julian-O/PySLOBS#5]
Hi,

i was wondering if there is an option to set the visibility of sources in a scene. I animated a little overlay for a game, which should be visible when ingame and invisible when i'm in the main menu. I searched throught the sourcesservice.py and source.py files to find a method which does that, but i could not find anything. I also tried to set every "visible" option in the properties to false and then update the source properties with "set_properties_form_data", but that did'nt work either, the settings were updated but the overlay was still visible. Can you help me out with that?
Thanks

**Comment by Julian-O** [comment]
I am not 100% confident I have understood what you have tried; hopefully this will help.

Each scene contains scene nodes. Each scene node is either a folder or a scene item, which *refers* to a source. That way different scenes can contain the same source (e.g. your logo or a chat box).

So you don't make a *source* invisible, you make a scene item inside a scene invisible.

- The steps are to find your scene (`listallscenes.py` or `spin.py` give examples of doing that.).
- Find the appropriate scene item (`spin.py` gives an example of that.)
- On the scene_item, you can call `set_visibility(False)`. If you want more granularity (i.e. independently affect whether YOU can see it, whether the stream can see it or whether your local recording can see it, `set_settings` can be used. An example of the use of `set_settings` can be seen in `ex_scenenodes.py`)

Unfortunately, there is no test code for `set_visible` yet, so I can't point to an example of it working, but I just did an ad hoc test and it is making the item invisible. (I found a separate bug, but that probably won't affect you!)

If this doesn't help, and there is an actual bug with PySlobs, happy to reopen this.

**Comment by IC0okieI** [comment]
Thank you very much.

I was not aware of scene items, i just used the scenes and sources as i would do it in streamlabs itself, so no subelements such as nodes or items.

But now everything works fine.
Thanks
