### ISSUE TITLE
AuthenticationFailure

### ISSUE THREAD

**Issue by hiro-551010** [Julian-O/PySLOBS#8]
This module will be very meaningful to me.
Thank you in advance.

I get an error with the following code.
```
File "D:\twitchbot\.venv\lib\site-packages\pyslobs\connection.py", line 104, in _authenticate
    raise AuthenticationFailure("%s" % response)
pyslobs.connection.AuthenticationFailure: {'id': 'auth_request', 'jsonrpc': '2.0', 'error': {'code': -32603, 'message': 'INTERNAL_JSON_RPC_ERROR Invalid token'}}
```
What kind of authentication is this supposed to be failing?

I've also included the ini file.
```
{pyslobs.ini}

[connection]
domain=localhost
port=59650
token=QRcode's APITOKEN
```
Sorry for my poor English.

**Comment by hiro-551010** [comment]
Does the ini file need an IP address?

**Comment by hiro-551010** [comment]
I solved it myself.
Thank you!

**Comment by Julian-O** [comment]
I am happy you were able to sort it out. Good luck with it!

I am guessing that the API Token was somehow copied incorrectly.

Just for the record, in case someone is looking at this later: Using "localhost" is fine. Using an IP address is fine. Omitting it entirely (and defaulting to localhost) is fine.
